- README.md
Full API Reference link is no longer valid.
Dead link: http://pyod.readthedocs.io/en/latest/api.html
Replaced with: https://pyod.readthedocs.io/en/latest/pyod.html
Kindly advise if not the preferred replacement link, or feel free to correct without this pull request. 
Thanks for creating this project!
> fix API reference link

- pyod/utils/utility.py
This was a little confusing for me working with this library, took me a while to figure out the function required raw scores instead of rounded ones (in which case it throws a precision being ill-defined error due to no predicted samples).
> Update for precision_n_scores docstring

- pyod/models/sod.py
Closes #114 
After doing some experiments on `SOD`, it turns out (as expected) that more than 95% of the extra time complexity is purely because of `snn()` function in `SOD` and more specifically the numpy function [isin()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.isin.html) used in `snn()`.
However, this function cannot be used under `numba` since [it is not supported](https://github.com/numba/numba/issues/3971) yet. 
I implemented a workaround to make it work under `numba`.
The results show noticeable improvement in time complexity and even faster than `Fast ABOD` algorithm.
Although `SOD` achieves a pretty good precision in high-dimensional spaces, nevertheless, please note that `SOD` is well-known to have relatively poor time complexity as many papers and …
> SOD Time Complexity Optimisation

- pyod/models/knn.py
Building query tree is available inside sklearn.NearestNeighbor._tree. Therefore, no need to rebuild.
> Building query tree can be skipped

- pyod/models/sod.py
I found  a bug in SOD, the data type of one of the lists was set to int16 causing overflow for large datasets. Changing it into int32 fixed the problem fully.
Please merge into master as soon as possible to avoid any confusion to the users because the bug was hidden and not throwing any error.
> fixed SOD bug due to a typo

- pyod/models/copod.py
this adds the feature explained in issue #260:
Addition of an optional keyword argument `feature_names` allows to set custom labels on the x-axis of the plot.
> Add option to specify feature names in copod explanation plot

- pyod/models/copod.py
When there are a lot of dimensions, the x axis in explain_outlier() becomes cluttered and impossible to read. This code adds "columns" optional argument where the user can put which exact columns of the dataset should be presented on the plot.
> Option to select columns in COPOD's explain_outlier()

- pyod/models/auto_encoder_torch.py
1. correct the std calculation function before preprocessing 
2. correct the PyODDataset
> correct the std calculation function and the PyODDataset

- pyod/models/lmdd.py
The current LMDD model implements the original paper method naively. 
Some easy optimizations are possible:
- "if var_max > res_[j] and if var_max > 0" can be collapsed into a single if statement because res_ is initialized as zeroes.
- var_max = self.dis_measure_(X[:i + 1]) - self.dis_measure_(X[:i]), because j = i, var_max is also equal to self.dis_measure_(X[:j + 1]) - self.dis_measure_(X[:j]), meaning we can replace these terms by var_max in the calculation of dk_diff.
- dk_diff >= var_max can be replaced by dk_diff - var_max >= 0
- We only need to add var_max into dk_diff if we actually assign it to res_[k], so the if statement can be further simplified. 
This PR implements these changes in the most basic manner, leading to a small speed increase.
> Added slight optimization to LMDD

- pyod/models/auto_encoder_torch.py
This pull request is a partial update to #375
As a first step, I cleaned the Autoencoder_Torch Docstring and Initialization in order to make clear and mention, that the learning rate is a valid parameter for the model. 
In the process, I also cleaned the code in the initialization and changed some wrong links (for tensorflow) to the corresponding Pytorch ones.
I did not alter any functionality, as learning rate was already supported (but very hidden).
With PyTorch it is difficult to pass an optimizer (with several changed parameters) as an instance since you need to tie it immediately to the model parameters.
Unfortunately, the model can only be initialized once the amount of features is known, which is only happening once the package user calls the fit function. This is also where the …
> Clean up docstring and initialization of Autoencoder_torch

- pyod/models/auto_encoder_torch.py
This Pullrequest is a proposal to fix #434.
I refactored the setup of the Autoencoder (PyTorch Version) in order to address the points of #434. The order of layers is now consistent with the Tensorflow implementation.
The order of Neurons->BatchNorm->Activation follows the Standard-Implementation of [ResNet](https://arxiv.org/abs/1512.03385)
> We adopt batch normalization (BN) [16] right after each convolution and before activation, following [16].
The printed Network now looks like:
<Details>
```
AutoEncoder(batch_norm=True, batch_size=32, contamination=0.1,
device=device(type='cpu'), dropout_rate=0.2, epochs=10,
hidden_activation='relu', hidden_neurons=[64, 32],
learning_rate=0.001, loss_fn=MSELoss(), preprocessing=True,
weight_decay=1e-05)
InnerAutoencoder(
(activation): ReLU() …
```
> Refactored PyTorch Autonencoder built up (Proposal to solve #434)

- pyod/models/alad.py
- pyod/models/anogan.py
Currently the y-label is overwritten and says 'Iter' instead of 'Loss'. This is a simple one line replacement to fix the plot labels for Anogan's plot_learning_curves plot.
> fix anogan plot_learning_curves label issue.

- pyod/models/cof.py
- pyod/models/mad.py
- pyod/models/rod.py
- pyod/models/sod.py
- pyod/models/sos.py
- pyod/test/test_cof.py
- pyod/test/test_mad.py
- pyod/test/test_rod.py
- pyod/test/test_sod.py
- pyod/test/test_sos.py
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>
This PR fixes all issues with pyod model cloning by ensuring that scikit-learn API requirements are followed. No logic has been changed. The previously commented out cloning tests have been reenabled and are passing, as well as other tests for the models changed.
Being able to clone models is critical for https://github.com/pycaret/pycaret, which uses pyod's models for its Anomaly Detection module.
> Fix all cloning issues with pyod models

- README.rst
- docs/install.rst
- docs/requirements.txt
- environment.yml
- pyod/models/copod.py
- pyod/models/ecod.py
- pyod/test/test_copod_parallel.py
- pyod/test/test_ecod_parallel.py
- pyod/test/test_stat_models.py
- pyod/utils/stat_models.py
- requirements.txt
Hey everyone,
as stated in #466 and in #453, one can speed up the empirical cumulative density function in comparison to the Statsmodels [ECDF functionality](https://www.statsmodels.org/dev/generated/statsmodels.distributions.empirical_distribution.ECDF.html).
This also makes the dependency on statsmodels obsolete and this pull request deletes the dependency.
In this pull request the following things are done:
1) **Implementing an standalone ecdf estimator** in [pyod/utils/stat_models.py](https://github.com/Lucew/pyod/blob/development/pyod/utils/stat_models.py)
2) Writing a [test](https://github.com/Lucew/pyod/blob/development/pyod/test/test_stat_models.py) that compares own implementation to statsmodels implementation on several random matrices (so in the requirements_ci.txt statsmodels …
> Implementing ECDF Estimator and deleting Statsmodels dependency

- CHANGES.txt
- examples/cd_example.py
- pyod/models/cd.py
- pyod/models/copod.py
- pyod/models/ecod.py
- pyod/test/test_cd.py
- pyod/version.py
I originally authored the Cook's distance outlier detection method on PyOD. But upon review, I realized that the method is not consistent with the rest of this library as the method is currently a supervised one. The changes made now have updated this method to be in line with the rest of the library by making it an unsupervised method. 
The most significant change is that instead of evaluating the model predictions against the response variable (y) the model now evaluates each variable in X against the rest of the variables in X and then computes the mean Cook's distance for each datapoint.
> Cooks distance unsupervised

- pyod/models/iforest.py
- pyod/test/test_iforest.py
* [OK ] Have you followed the guidelines in our Contributing document?
* [ OK] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ OK] Have you checked all [Issues](../../issues) to tie the PR to a specific one?
* [ OK] Have you added an explanation of what your changes do and why you'd like us to include them?
Added some properties to the IForest class so that new methods for IForest implementing the DIFFI algorithm, that will be inserted in a future Pull Request, can work also on objects of the IForest class 
* [OK ] Have you written new tests for your core changes, as applicable?
* [OK ] Have you successfully ran tests with your changes locally?
* [OK ] Does your submission have appropriate code coverage? The cutoff threshold …
> Update IForest model 

- README.rst
Just a small PR to make the readme badges be on one line.
I was just sharing with a colleague and noticed the badges seem to each be on thier own line in the github readme. Thought could be an easy one for me to try see if can make a little prettier potentially as i love the project.
Can quickly see how it will look here: https://github.com/andrewm4894/pyod/blob/patch-1/README.rst
> make readme badges be on one line

- pyod/__init__.py
PyOD has no `pyod.__version__` property, which makes integrating it in other packages complicated. Many tools use `<module>.__version__` to check compatibility at runtime.
PyOD already stores the version number in code, but in a non-standard location (`pyod.version.__version__`). This PR just pulls the `__version__` in the module's global namespace.
There is #295, which is open for 3 years and entirely changes the versioning of PyOD.
In contrast, this PR is a minor change.
Fixes #253
> Add pyod.__version__ property

- docs/index.rst
It seems this pdf link was 404'd and so I found the same pdf on arxiv. You can confirm the pdf is the same through the wayback machine https://web.archive.org/web/20221101105425/https://www.andrew.cmu.edu/user/yuezhao2/papers/22-neurips-adbench.pdf
> Fixing pdf link

- pyod/models/qmcd.py
Hi, this PR addresses the Issue https://github.com/yzhao062/pyod/issues/549
All the previous functionality still exists. 
Notable changes include: returned decision scores are no longer normalized, better criterion for switching the scores when necessary, exposing the ``decision_function`` to correctly handle new data not seen during the OD fitting.
**Note** that the last change above will cause the model to hold more memory as the original dataset must be stored as variable with which to compare the new data to. This will affect a stored joblib model size if created.
If there are any issues let me know and am happy to make the necessary changes.
> QMCD normalization fix

- examples/ae1svm_example.py
- pyod/models/ae1svm.py
- pyod/models/mo_gaal.py
- pyod/test/test_ae1svm.py
> Added new model ae1svm & updated author info

- pyod/models/ae1svm.py
> Updated ae1svm comments w/ parameters descriptions

- pyod/models/alad.py
- pyod/test/test_alad.py
> pytorch version alad update

- setup.cfg
This fixes the install error happening on setuptools 0.78: `setuptools.errors.InvalidConfigError: Invalid dash-separated key 'description-file' in 'metadata' (setup.cfg), please use the underscore name 'description_file' instead.`
Closes https://github.com/yzhao062/pyod/issues/630
> Change deprecated property name for setup

- pypi_build_commands.txt
- direct invocation of setup.py is deprecated
- publish wheels, rather than making every consumer of the package build a wheel
Before `python -m build` you may need to `pip install build` or equivalent (just as you need to install twine before running twine).
> publish wheels
