README.rst, docs/index.rst
Small tests on the development branch.
=> Refactor documentation documentation

pyod/models/iforest.py
=> Fix for sklearn new behaviour FutureWarning

CHANGES.txt, README.rst, docs/index.rst, docs/zreferences.bib, pyod/models/base.py, pyod/models/mo_gaal.py, pyod/models/so_gaal.py, pyod/version.py
=> v0.7.1 Minor documentation fix and installation fix

pyod/models/mo_gaal.py, pyod/models/so_gaal.py
By this commit I fix `fit` method of SO_GAAL model. And also make both `fit` methods of SO_GAAL and MO_GALL models look more consistent by adding `return self` line in the end of MO_GALL's `fit` method
=> Fix SO_GAAL fitting method

pyod/models/cblof.py
=> correction for CBLOF small big cluster definition code error

pyod/models/cblof.py
Reverts yzhao062/pyod#95 Should be submitted to development branch.
=> Revert "correction for CBLOF small big cluster definition code error"

CHANGES.txt, docs/requirements.txt, pyod/models/loda.py, pyod/models/sod.py, pyod/models/xgbod.py, pyod/version.py
=> Development V0.7.8.2

environment.yml
This PR attempts to fixes the Binder Setup.
`combo` and `soud` seems to be not available in `conda`. The modifications in the `environment.yml` install them from `pip`, on top of the conda setup.
=> Fixes the Binder setup.

README.rst
just started using this library and ran into the missing import, I think this edit helps to get the intro examples to run out of the box
* [x ] Have you followed the guidelines in our Contributing document?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?
=> missing import

pyod/models/lscp.py
This fixes the Issue #180 by reducing the preset `local_region_threshold` until at least 2 values are contained in each element of the `final_local_region_list`.
=> Fix for LSCP (Issue #180)

examples/generate_data_categorical_example.py, pyod/test/test_data.py, pyod/utils/data.py
Closes #101 
----------------------
The idea of the algorithm is to create a pool of features based on the number of features passed by user. 
This pool will be the base of generating all categorical data.
Also, the user can specify the number of categories  in the normal points and in the outliers.
Added to that, the user can specify the number of informative features in the outlier points in which the higher the easier to detect and classify, whereas the lower the more redundant (non-informative and insignificant) the features in the outlier points which makes it more difficult to detect.
Required tests and example have been added.
=> Generate Synthesized Categorical Data

examples/rod_example.py, pyod/models/rod.py, pyod/test/test_rod.py
--------------------------------------------
Rotation-based Outlier Detection (ROD), is a robust and parameter-free algorithm that requires no statistical distribution assumptions and works intuitively in three-dimensional space, where the 3D-vectors, representing the data points, are rotated about the geometric median two times counterclockwise using Rodrigues rotation formula. The results of the rotation are parallelepipeds where their volumes are mathematically analyzed as cost functions and used to calculate the Median Absolute Deviations to obtain the outlying score. For high dimensions > 3, the overall score is calculated by taking the average of the overall 3D-subspaces scores, that were resulted from decomposing the original data space.
ROD precision in classifying outliers was …
=> ROD Algorithm

examples/sos_example.py
=> Docstring added.

.travis.yml, pyod/version.py
=> V0.8.9. (test env update)

examples/rod_example.py, pyod/models/rod.py, pyod/test/test_rod.py
-------------------------------
In the previous implementation, ROD was re-fitting every time `predict()` is called, and was not maintaining/keeping what it has learned from `fit()`. Now it's fixed and tested.
=> ROD Hot Fixes

pyod/models/lof.py
Adding the missing parameter fixes the issue #244.
=> Fix for Issue #244

pyod/models/rod.py, pyod/test/test_rod.py
-------------------------------------------------------
From previous hot fix, MAD median was still left out without being saved after invoking `fit()`, now it is saved and tested so it is fully compatible with `PyOD` and `Sklearn` code convention.
=> ROD Hot Fix

docs/zreferences.bib, examples/deepsvdd_example.py, pyod/models/deep_svdd.py, pyod/test/test_deepsvdd.py
=> Deepsvdd implementation #284

.circleci/config.yml, .travis.yml, CHANGES.txt, appveyor.yml, setup.py
=> Expand the coverage to Python 3.8&3.9

pyod/models/mad.py, pyod/test/test_mad.py
=> Correct MAD behaviour in prediction

examples/comb_example.py
Doesn't change any results actually, but naming is a little misleading.
=> correct naming of median combination in comb_example.py

pyod/models/iforest.py
=> Recover feature importances from detector

CHANGES.txt, README.rst, docs/index.rst, docs/zreferences.bib, examples/iforest_example.py, pyod/models/iforest.py, pyod/test/test_iforest.py, pyod/version.py
=> V0.9.8 Add ECOD 

CHANGES.txt, pyod/models/copod.py, pyod/models/ecod.py, pyod/version.py
=> urgent fix for nan in ECOD and COPOD

pyod/models/base_dl.py, pyod/test/test_base_dl.py, pyod/test/test_torch_utility.py, pyod/utils/torch_utility.py
=> Implement PyTorch deep learning base detector and utility functions.

docs/api_cc.rst
Where is the document, I didn't find it ? 
It is just a minor update to fix a citation.
Have a nice day.
=> fix ALZB+20 citation

pyod/models/so_gaal.py
=> minor fix on sogaal (handling large dataset)

README.rst
Fix link to NLP-ADBench in README
=> Fix link to NLP-ADBench

docs/about.rst
=> fix doc issue
